create database task1;
use task1;
create table student(Roll_No int,Name varchar(20),Phone_number bigint);
insert into student values(1,"Gopi",8610533383),(2,"Ram",9345278619),(3,"John",8765432109);
select * from student;
alter table student add age int;
alter table student modify Phone_number varchar(20);
select * from student;
update student set age=20;
select * from student;
update student set age=21 where Name="John";
select * from student;
alter table student change Phone_number Mobile_number varchar(20);
select * from student;
alter table student drop column age;
select * from student;
rename table student to studetails;
select * from student;
select * from studetails;
delete from studetails where Roll_NO=3;
select * from studetails;
truncate table studetails;
select * from studetails; 
drop table studetails;
select * from studetails;